name: cached_map_marker
description: "Optimizes Google map markers by caching, managing custom markers."
version: 0.0.1
homepage: https://github.com/ahmedsaleh210/cached_map_marker
repository: https://github.com/ahmedsaleh210/cached_map_marker
license: MIT

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.2
  google_maps_flutter: ^2.7.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter: null
